# Generated by Django 4.1.2 on 2023-10-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_blog_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='blog',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='total_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
